FROM mcr.microsoft.com/devcontainers/java:11-bullseye

ARG EXIST_VERSION=6.2.0
ARG TEMPLATING_VERSION=1.1.0
ARG PUBLISHER_LIB_VERSION=4.0.0
ARG ROUTER_VERSION=1.8.1
ARG EDITOR_VERSION=1.0.1

ARG HTTP_PORT=8080
ARG HTTPS_PORT=8443

# Install OS packages needed for the build. Retry apt-get update so a flaky
# Debian mirror (intermittent "exit code 100") does not fail the whole build.
RUN export DEBIAN_FRONTEND=noninteractive \
    && (apt-get update || apt-get update || apt-get update --fix-missing) \
    && apt-get -y install --no-install-recommends bzip2 python3-pip \
    && pip3 install --upgrade pip

# Install Ant for building TEI Publisher libraries
RUN su vscode -c "source /usr/local/sdkman/bin/sdkman-init.sh && sdk install ant"
ENV ANT_HOME=/usr/local/sdkman/candidates/ant/current
ENV PATH=${PATH}:${ANT_HOME}/bin

# [Option] Install Node.js
ARG INSTALL_NODE="true"
ARG NODE_VERSION="lts/*"
RUN if [ "${INSTALL_NODE}" = "true" ]; then su vscode -c "source /usr/local/share/nvm/nvm.sh && nvm install ${NODE_VERSION} 2>&1"; fi

# [Optional] Uncomment this line to install global node packages.
# RUN su vscode -c "source /usr/local/share/nvm/nvm.sh && npm install -g <your-package-here>" 2>&1

WORKDIR /workspaces

# Download and install eXist-db
RUN curl -L -o exist-distribution-${EXIST_VERSION}-unix.tar.bz2 https://github.com/eXist-db/exist/releases/download/eXist-${EXIST_VERSION}/exist-distribution-${EXIST_VERSION}-unix.tar.bz2 \
    && tar xfj exist-distribution-${EXIST_VERSION}-unix.tar.bz2 -C /usr/local \
    && rm exist-distribution-${EXIST_VERSION}-unix.tar.bz2 \
    && mv /usr/local/exist-distribution-${EXIST_VERSION} /usr/local/exist

# If tei-publisher-lib version is "master", build it. Otherwise download the specified version.
RUN if [ "${PUBLISHER_LIB_VERSION}" = "master" ]; then \
        git clone https://github.com/eeditiones/tei-publisher-lib.git \
        && cd tei-publisher-lib \
        && ant \
        && cp build/*.xar /usr/local/exist/autodeploy; \
    else \
        curl -L -o /usr/local/exist/autodeploy/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/tei-publisher-lib-${PUBLISHER_LIB_VERSION}.xar; \
    fi

RUN curl -L -o /usr/local/exist/autodeploy/roaster-${ROUTER_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/roaster-${ROUTER_VERSION}.xar
RUN curl -L -o /usr/local/exist/autodeploy/templating-${TEMPLATING_VERSION}.xar https://exist-db.org/exist/apps/public-repo/public/templating-${TEMPLATING_VERSION}.xar
RUN curl -L -o /usr/local/exist/autodeploy/atom-editor-${EDITOR_VERSION}.xar https://github.com/wolfgangmm/existdb-langserver/raw/master/resources/atom-editor-${EDITOR_VERSION}.xar

WORKDIR /usr/local/exist
ENV JAVA_HOME=/usr/lib/jvm/msopenjdk-current

RUN bin/client.sh -l --no-gui --xpath "system:get-version()"

EXPOSE ${HTTP_PORT} ${HTTPS_PORT} 8001

ENV EXIST_HOME=/usr/local/exist
ENV JAVA_OPTS \
    -Djetty.port=${HTTP_PORT} \
    -Djetty.ssl.port=${HTTPS_PORT} \
    -Dfile.encoding=UTF8 \
    -Dsun.jnu.encoding=UTF-8 \
    -XX:+UseG1GC \
    -XX:+UseStringDeduplication \
    -XX:+UseContainerSupport \
    -XX:MaxRAMPercentage=${JVM_MAX_RAM_PERCENTAGE:-75.0} \
    -XX:+ExitOnOutOfMemoryError

ENTRYPOINT [ "/usr/local/exist/bin/startup.sh" ]